### ISSUE TITLE
hyperscan版本问题和链接fsst、fse问题请教

### ISSUE THREAD

**Issue by benzhaotang** [antgroup/pbc#1]
环境：阿里云租的服务器
2核(vCPU)
4 GiB
1 Mbps
[ecs.e-c1m2.large]
![image](https://github.com/user-attachments/assets/f590684d-508f-45bc-87c2-8fb5437fc42a)
系统：Ubuntu 20.04.6 LTS

在执行./build.sh -r 时遇到以下两个问题
1.build hyperscan时的版本问题（可以解决）
在hyperscan.cmake中将5.4.0改为5.4.2，并修改md5为202f4b42f5dd4a7bb2506445e51a33b9

2.链接fsst、fse问题（未解决）
+ make -j4
[  3%] Building CXX object src/deps/fsst/CMakeFiles/pbc_fsst.dir/libfsst.cpp.o
[  7%] Building CXX object src/deps/fsst/CMakeFiles/pbc_fsst.dir/fsst_avx512.cpp.o
[ 10%] Building C object src/deps/fse/CMakeFiles/pbc_fse.dir/debug.c.o
[ 14%] Building C object src/deps/fse/CMakeFiles/pbc_fse.dir/entropy_common.c.o
[ 17%] Building C object src/deps/fse/CMakeFiles/pbc_fse.dir/fseU16.c.o
[ 21%] Building C object src/deps/fse/CMakeFiles/pbc_fse.dir/fse_compress.c.o
[ 25%] Building C object src/deps/fse/CMakeFiles/pbc_fse.dir/fse_decompress.c.o
[ 28%] Building C object src/deps/fse/CMakeFiles/pbc_fse.dir/hist.c.o
[ 32%] Building C object src/deps/fse/CMakeFiles/pbc_fse.dir/huf_compress.c.o
[ 35%] Building C object src/deps/fse/CMakeFiles/pbc_fse.dir/huf_decompress.c.o
[ 39%] Linking CXX static library libpbc_fsst.a
Error running link command: No such file or directory
make[2]: *** [src/deps/fsst/CMakeFiles/pbc_fsst.dir/build.make:114：src/deps/fsst/libpbc_fsst.a] 错误 2
make[1]: *** [CMakeFiles/Makefile2:261：src/deps/fsst/CMakeFiles/pbc_fsst.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 42%] Linking C static library libpbc_fse.a
Error running link command: No such file or directory
make[2]: *** [src/deps/fse/CMakeFiles/pbc_fse.dir/build.make:210：src/deps/fse/libpbc_fse.a] 错误 2
make[1]: *** [CMakeFiles/Makefile2:235：src/deps/fse/CMakeFiles/pbc_fse.dir/all] 错误 2
make: *** [Makefile:146：all] 错误 2

希望可以告知问题原因和解决办法

**Comment by St3phZhang** [comment]
应该是有东西没装好, 先“apt install cmake clang lldb llvm-dev lld libboost-all-dev”再编译
